name: build

on:
  push:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest on main
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Remove / form github.ref_name
        run: |
          a=${{ github.ref_name }}
          echo "branch_name=${a//\//-}" >> $GITHUB_ENV

      # PR opened by dependabot can't push. I didn't find other way
      # to avoid it

      - name: Check if 'dependabot' is in branch name
        run: echo "IS_NOT_DEPENDABOT=$([[ $(echo ${{ env.branch_name }}) == *dependabot* ]] && echo "false" || echo "true")" >> $GITHUB_ENV

      - name: Build and push with ref name
        uses: docker/build-push-action@v3
        with: 
          context: .
          push: ${{ env.IS_NOT_DEPENDABOT }}
          tags: ghcr.io/${{ github.repository }}:${{ env.branch_name }}
